yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  'eslint-config-react-app@7.0.1':
    dependencies:
      '@babel/plugin-syntax-flow': "7.14.5"
      '@babel/plugin-transform-react-jsx': "7.14.9"
